<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <Target Name="ILRepacker" AfterTargets="Build">
        <ItemGroup>
            <InputAssemblies Include="$(TargetPath)" />
            <InputAssemblies Include="$(OutputPath)YamlDotNet.dll" />
            <InputAssemblies Include="$(OutputPath)ServerSync.dll" />
            <InputAssemblies Include="$(OutputPath)AzuExtendedPlayerInventoryAPI.dll" />
            <LibraryPath Include="$(OutputPath)" />
            <LibraryPath Include="$(GameDir)\BepInEx\core" />
            <LibraryPath Include="$(GameDir)\valheim_Data\Managed" />
            <LibraryPath Include="$(GameDir)\valheim_Data\Managed\publicized_assemblies" />
        </ItemGroup>
        <ILRepack Parallel="true" DebugInfo="true" Internalize="true" InputAssemblies="@(InputAssemblies)" OutputFile="$(TargetPath)" TargetKind="SameAsPrimaryAssembly" LibraryPath="@(LibraryPath)" />
    </Target>
</Project>
